### ISSUE TITLE
Error training new model.

### ISSUE THREAD

**Issue by hurnhu** [ConorLazarou/PokeGAN#9]
I fairly new to NN's in general, so forgive my ignorance. 

i've dropped in images into the sprites folder.

but when i run the main.py i get this error.

`Epoch 1; Elapsed time = 00:00:00s
Traceback (most recent call last):
  File "main.py", line 113, in <module>
    main()
  File "main.py", line 90, in main
    gan.train_epoch(max_steps=100)
  File "/home/michael/nft/PokeGAN/aegan.py", line 645, in train_epoch
    ldx_, ldz_ = self.train_step_discriminators(real_samples)
  File "/home/michael/nft/PokeGAN/aegan.py", line 605, in train_step_discriminators
    Z_hat = self.encoder(X)
  File "/home/michael/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/michael/nft/PokeGAN/aegan.py", line 357, in forward
    down = intermediate.view(-1, 6*6*512)
RuntimeError: shape '[-1, 18432]' is invalid for input of size 4194304
`

also once it is trained, how would i go abount generating a single image from the trained model?

Thanks!

**Comment by ConorLazarou** [comment]
Whoops, looks like I had a typo in there. This has been fixed in the latest commit. Thanks for pointing this out!
